---
ServerAPI:
  Addr: 192.168.122.49
  Port: 24601
  PrivateKey: "/opt/vaquero/secret/server.key"
  PublicKey: "/opt/vaquero/secret/server.pem"
ServerClient:
  Addr: 192.168.122.49
  Port: 24601
  InsecureSkipVerify: true
#SavePath: "/var/vaquero"
LocalDir:
  PollInterval: 1

# Define one of LocalDir or Etcd endpoints.
Etcd:
  Endpoints:
  - "http://192.168.122.49:2379"
  Timeout: 5
  Retry: 3

SoT:
- Local:
    ID: vaquero-local
    Root: /opt/vaquero_inventory/local
Log:
  Level: debug
  Location: stdout
  Type: text
